### ISSUE TITLE
Implementing a method to get a print version

### ISSUE THREAD

**Issue by marcelodeandrade** [fruppel/yii2-googlecharts#6]
I need sendo a chart to email, and the method to convert a chart to image is don't acessible. To create a method in wrapper to access the [getImageURI()](https://developers.google.com/chart/interactive/docs/printing)

**Comment by fruppel** [comment]
I will definitely have a look at it but I can't promise that it's even possible. Simplest solution would be to make that chart variable global so that you can write your own JavaScript to get the image data URI. But at first I will try to add an option to the PHP code so that it can output the data URI.

**Comment by fruppel** [comment]
With the new release v1.1.0 you can now set the option $asPng to true to output an chart as png. But note that the chart is first rendered with the google charts API in the canvas element and then transformed to PNG. Sadly there is no way to get the PNG (or at least the image URI) directly (without creating the chart first) so I don't know how much it helps with your email application.

**Comment by marcelodeandrade** [comment]
Oh! it is a great help, sadly don't solved my problem but thank you, i will searching for a way to do this.
